### ISSUE TITLE
Cancelled payments result in confirmed order mails

### ISSUE THREAD

**Issue by YellowlimeNL** [ingpsp/magento#14]
We run this extension on a 1.7.0.2 installation. In case payment of an order is aborted by the client and client is returned to the webstore, an order confirmation mail is sent out to client and shop owner. The webhook we use in the Kassa Compleet configuration is https://www.example.com/ingpsp/ideal/webhook.

How can we prevent oder confirmation mails sent out as order is not a confirmed order yet.

**Comment by Frank-Magmodules** [comment]
Hi @YellowlimeNL, thank you for the issue report. Just reproduced this issue and we are working on an update. This update will be available somewhere in the next couple of days.

**Comment by Frank-Magmodules** [comment]
![ing-email](https://user-images.githubusercontent.com/24823946/52858800-7783ec80-312b-11e9-90ef-64467086c072.gif)

Hi @YellowlimeNL , we've just released a new version with the following changelog;

- **Added option to select when the order email will be sent**
- Disabled payment method check in Admin
- Replaced exception for error message with a redirect to cart

Please see version [1.4.3](**url**).

**Comment by YellowlimeNL** [comment]
Thank you for the quick fix, this indeed solves the issue we were facing.

**Comment by YellowlimeNL** [comment]
Hi Frank,

Thank you for the quick fix, this indeed solves the issue we were facing.

Best regards,

Thijs
Yellowlime

Kobaltweg 38
3542 CE Utrecht

T 030-7070155 - thijs@yellowlime.nl - www.yellowlime.nl
